### PR TITLE
fix: hide password

### PR DESCRIPTION
**Pull request by zmstone**
This PR is to make eredis' `start_link` functions accept anonymous function in the args for password.
It also tries to wrap plaintext passwords in an anonymous function to avoid future changes to log arguments or states to logs.

### CODE REVIEW

**Review by thalesmg — APPROVED** [review]
Should there be a `code_upgrade` that wraps the password for already running processes?

**Review by terry-xiaoyu — APPROVED** [review]

**Review by terry-xiaoyu — APPROVED** [review]

**Comment by zmstone** [comment]
> Should there be a `code_upgrade` that wraps the password for already running processes?

That would be perfect, but we so far don't have solid evidens that eredis is currently dumping the passwords to logs.
This change is mostly to extend the APIs to accept a `#Fun<...>` as input.

**Comment by zmstone** [comment]
> > Should there be a `code_upgrade` that wraps the password for already running processes?
> 
> That would be perfect, but we so far don't have solid evidens that eredis is currently dumping the passwords to logs. This change is mostly to extend the APIs to accept a `#Fun<...>` as input.

A second thought. Downgrad will be problematic. Will fix it in another PR.

**Comment by zmstone** [comment]
This PR has been reverted on master branch (by hard-resetting to commit 1.2.8).
The reason is that the password wrap in `#state{}` are impossible to downgrade.

**Pull request merged**
